[general]
id = "sd1-ff00_0_132"
config_dir = "gen/ASff00_0_132"

[trust_db]
connection = "gen-cache/sd1-ff00_0_132.trust.db"

[path_db]
connection = "gen-cache/sd1-ff00_0_132.path.db"

[sd]
address = "127.0.0.132:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "127.0.0.132:30455"

[features]

[api]
addr = "127.0.0.132:30955"

[log.console]
level = "debug"
