[general]
id = "sd2-ff00_0_222"
config_dir = "gen/ASff00_0_222"

[trust_db]
connection = "gen-cache/sd2-ff00_0_222.trust.db"

[path_db]
connection = "gen-cache/sd2-ff00_0_222.path.db"

[sd]
address = "127.0.0.204:30255"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "127.0.0.204:30455"

[features]

[api]
addr = "127.0.0.204:30955"

[log.console]
level = "debug"
